### ISSUE TITLE
Simulation prints a lot of stuff into stdout

### ISSUE THREAD

**Issue by DmytroTym** [ZenGo-X/round-based-protocol#5]
In `simulation.rs`, methods `proceed_if_needed` and `handle_incoming` print a lot, especially if the number of parties is large. This is done via `println!` and thus not very configurable, complicating debug, testing and benchmarking. Maybe we can use `info!` or `debug!` instead? I can make a PR for this

**Comment by survived** [comment]
You're right, it's quite inconvenient. We're currently working on major revision of this crate, and a [new simulation] already has no printing. However, if you'd like to fix current version, PR is more than welcome!

[new simulation]: https://github.com/ZenGo-X/round-based-protocol/blob/round-based2/round-based/src/simulation.rs

**Comment by DmytroTym** [comment]
I did a quick PR, changing printins to debugs: https://github.com/ZenGo-X/round-based-protocol/pull/6
I now see the limitations of this approach: it's pretty hard to set log level in tests :(
Still, maybe it works as a temporary measure?

**Comment by survived** [comment]
@DmytroTym a [new version] with your changes is published!

[new version]: https://crates.io/crates/round-based
