### ISSUE TITLE
Access the state machine from `AsyncProtocol`?

### ISSUE THREAD

**Issue by shekohex** [ZenGo-X/round-based-protocol#8]
### Question
Hello is there a way to access the state machine after moving It to the `AsyncProtocol`? Looks like there is no way right now, the ProtocolWatcher is still limited only for errors, and I can't wrap the state in `Arc` or `Arc`+`RwLock` since the base `StateMachine` trait does not implement for both these wrapped types (However I can wrap mine in my own type, but that's a lot of boilerplate code).

### What I'm trying to achieve or my use case

I want to be able to call [`round_blame`](https://github.com/ZenGo-X/multi-party-ecdsa/blob/9193fb7d42178fe854688b1874a9a7cd61b540c9/src/protocols/multi_party_ecdsa/gg_2020/state_machine/traits.rs#L5) on the Keygen or the OfflineStage for example when I see that the current Round failed, so I can know which parties are responsible for that.

### What we can do to improve the API?

* One thing could be when the `AsyncProtocol` finishes [here](https://github.com/ZenGo-X/round-based-protocol/blob/main/src/async_runtime/mod.rs#L108) it returns the state result and the state itself.
* Another option is to allow immutable access to the underlying state from the `AsyncProtocol`.
* A third option would be by extending the API for the [`ProtocolWatcher`](https://docs.rs/round-based/0.1.6/round_based/async_runtime/watcher/trait.ProtocolWatcher.html) with a way to call back when either the rounds timeout, stopped or failed with an immutable reference to the current state.

> IMO the third option makes more sense and would be the cleanest way to do so.

**Comment by shekohex** [comment]
It looks like even wrapping the state in our own types will not work since the `StateMachine` trait is not designed for that either, for example, if I try to do the following:

```rust
pub(crate) struct SharedStateMachine<T> {
    sm: Arc<RwLock<T>>,
}

impl<T> Clone for SharedStateMachine<T> {
    fn clone(&self) -> Self {
        Self {
            sm: Arc::clone(&self.sm),
        }
    }
}

impl<T> StateMachine for SharedStateMachine<T>
where
    T: StateMachine,
{
    type MessageBody = T::MessageBody;

    type Err = T::Err;

    type Output = T::Output;

    fn handle_incoming(&mut self, msg: Msg<Self::MessageBody>) -> Result<(), Self::Err> {
        let mut this = self.sm.write();
        this.handle_incoming(msg)
    }

    fn message_queue(&mut self) -> &mut Vec<Msg<Self::MessageBody>> {
        let mut this = self.sm.write();
        // here, it will not work ofc, rustc says:
        // cannot return reference to local variable `this` returns a reference to data owned by the
        // current function
        this.message_queue()
    }

    fn wants_to_proceed(&self) -> bool {
        self.sm.read().wants_to_proceed()
    }

    fn proceed(&mut self) -> Result<(), Self::Err> {
        self.sm.write().proceed()
    }

    fn round_timeout(&self) -> Option<std::time::Duration> {
        self.sm.read().round_timeout()
    }

    fn round_timeout_reached(&mut self) -> Self::Err {
        self.sm.write().round_timeout_reached()
    }

    fn is_finished(&self) -> bool {
        self.sm.read().is_finished()
    }

    fn pick_output(&mut self) -> Option<Result<Self::Output, Self::Err>> {
        self.sm.write().pick_output()
    }

    fn current_round(&self) -> u16 {
        self.sm.read().current_round()
    }

    fn total_rounds(&self) -> Option<u16> {
        self.sm.read().total_rounds()
    }

    fn party_ind(&self) -> u16 {
        self.sm.read().party_ind()
    }

    fn parties(&self) -> u16 {
        self.sm.read().parties()
    }
}
```

**Comment by survived** [comment]
Hey, thanks for reaching out and providing structured feedback! Indeed that's something that can be improved. 

I personally like idea of adding a getter to `AsyncProtocol`:
```rust
impl AsyncProtocol<SM, ..> {
    pub fn state_machine_ref(&self) -> Result<&SM, Error>;
    pub fn into_state_machine(self) -> Result<SM, Error>;
}
```

Note that they might return an error. Actual state might be missing only in one case: `state_machine.proceed()` panicked. Proceeding is some protocol-specific computationally heavy action that we execute on a dedicated thread, so if it panics, we are not able to retrieve the state back.

Would that address your use-case?

**Comment by survived** [comment]
Extending ProtocolWatcher is an option too, I left it minimalistic by intention to extend it later. However it was designed for tracing purposes (e.g. log state changes to debug it). It feels like providing a getter is what you actually need.

**Comment by survived** [comment]
Another pros of providing getter method vs extending ProtocolWatcher is that adding new methods to a structure doesn't require major version bump, so we do not need to update `multi-party-ecdsa` library. Adding new methods to a trait usually requires major bump unless we provide default implementation of these methods.

**Comment by shekohex** [comment]
> Would that address your use-case?

Yes, I guess so! we can go with that.

**Comment by survived** [comment]
Would you add a getter in PR?

**Comment by shekohex** [comment]
Alright, I will create a small PR.

**Comment by survived** [comment]
New version is published! You can try it out in your project by updating dependency: `cargo update -p round-based`.
